# Generated by Django 5.0.3 on 2024-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmstAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('recognize_people', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=20)),
                ('ww1', models.IntegerField()),
                ('count_backwards', models.CharField(max_length=255)),
                ('repeat_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('date', models.DateField()),
                ('mobile_num', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=255)),
                ('additional_tests', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
