# Generated by Django 5.0.3 on 2024-11-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmseAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('season', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=100)),
                ('backward', models.CharField(max_length=100)),
                ('recall', models.CharField(max_length=100)),
                ('objects_outside', models.CharField(max_length=100)),
                ('phrase', models.CharField(max_length=255)),
            ],
        ),
    ]
